version: '1'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: book
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  products:
    image: products
    container_name: products
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL:jdbc:mysql://localhost:3306/railway}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:root}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:pwd}
    depends_on:
      - mysql

volumes:
  mysql-data: